### ISSUE TITLE
Disabled countries are available in checkout

### ISSUE THREAD

**Issue by JoachimTorngren** [PaysonAB/Payson-Checkout2-Opencart-2-3#4]
During checkout it is possible to select a country (for example Mongoliet) even though it is not enabled in the store settings (localization-countries).

![payson_161228_countries](https://cloud.githubusercontent.com/assets/14246807/21521123/3bc56c38-ccfa-11e6-85b1-a1aadca1a498.jpg)

**Comment by PaysonAB** [comment]
Hi JoachimTorngren,

This channel is currently not watched by our integration department. Please send your bug reports, questions, and input, to integration@payson.se<mailto:integration@payson.se> .

/Payson Tech

Från: JoachimTorngren [mailto:notifications@github.com]
Skickat: den 28 december 2016 12:37
Till: PaysonAB/Payson-Checkout2-Opencart-2-3 <Payson-Checkout2-Opencart-2-3@noreply.github.com>
Kopia: Subscribed <subscribed@noreply.github.com>
Ämne: [PaysonAB/Payson-Checkout2-Opencart-2-3] Too many countries available (#4)


During checkout it is possible to select a country (for example Mongoliet) even though it is not enabled in the store settings (localization-countries).

[payson_161228_countries]<https://cloud.githubusercontent.com/assets/14246807/21521123/3bc56c38-ccfa-11e6-85b1-a1aadca1a498.jpg>
